import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { Press_Start_2P } from 'next/font/google';

import '../styles/main.scss';
// import './globals.css';

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
});

const pressStart2P = Press_Start_2P({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-press-start',
});


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${pressStart2P.variable}`}>{children}</body>
    </html>
  );
}
